//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace TeamKeep.Models.DataModels
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DatabaseEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DatabaseEntities object using the connection string found in the 'DatabaseEntities' section of the application configuration file.
        /// </summary>
        public DatabaseEntities() : base("name=DatabaseEntities", "DatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DatabaseEntities object.
        /// </summary>
        public DatabaseEntities(string connectionString) : base(connectionString, "DatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DatabaseEntities object.
        /// </summary>
        public DatabaseEntities(EntityConnection connection) : base(connection, "DatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GameData> GameDatas
        {
            get
            {
                if ((_GameDatas == null))
                {
                    _GameDatas = base.CreateObjectSet<GameData>("GameDatas");
                }
                return _GameDatas;
            }
        }
        private ObjectSet<GameData> _GameDatas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GameLocationData> GameLocationDatas
        {
            get
            {
                if ((_GameLocationDatas == null))
                {
                    _GameLocationDatas = base.CreateObjectSet<GameLocationData>("GameLocationDatas");
                }
                return _GameLocationDatas;
            }
        }
        private ObjectSet<GameLocationData> _GameLocationDatas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PlayerData> PlayerDatas
        {
            get
            {
                if ((_PlayerDatas == null))
                {
                    _PlayerDatas = base.CreateObjectSet<PlayerData>("PlayerDatas");
                }
                return _PlayerDatas;
            }
        }
        private ObjectSet<PlayerData> _PlayerDatas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PlayerGroupData> PlayerGroupDatas
        {
            get
            {
                if ((_PlayerGroupDatas == null))
                {
                    _PlayerGroupDatas = base.CreateObjectSet<PlayerGroupData>("PlayerGroupDatas");
                }
                return _PlayerGroupDatas;
            }
        }
        private ObjectSet<PlayerGroupData> _PlayerGroupDatas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SeasonData> SeasonDatas
        {
            get
            {
                if ((_SeasonDatas == null))
                {
                    _SeasonDatas = base.CreateObjectSet<SeasonData>("SeasonDatas");
                }
                return _SeasonDatas;
            }
        }
        private ObjectSet<SeasonData> _SeasonDatas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TeamData> TeamDatas
        {
            get
            {
                if ((_TeamDatas == null))
                {
                    _TeamDatas = base.CreateObjectSet<TeamData>("TeamDatas");
                }
                return _TeamDatas;
            }
        }
        private ObjectSet<TeamData> _TeamDatas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TeamOwnerData> TeamOwnerDatas
        {
            get
            {
                if ((_TeamOwnerDatas == null))
                {
                    _TeamOwnerDatas = base.CreateObjectSet<TeamOwnerData>("TeamOwnerDatas");
                }
                return _TeamOwnerDatas;
            }
        }
        private ObjectSet<TeamOwnerData> _TeamOwnerDatas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TeamPrivacyData> TeamPrivacyDatas
        {
            get
            {
                if ((_TeamPrivacyDatas == null))
                {
                    _TeamPrivacyDatas = base.CreateObjectSet<TeamPrivacyData>("TeamPrivacyDatas");
                }
                return _TeamPrivacyDatas;
            }
        }
        private ObjectSet<TeamPrivacyData> _TeamPrivacyDatas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UserData> UserDatas
        {
            get
            {
                if ((_UserDatas == null))
                {
                    _UserDatas = base.CreateObjectSet<UserData>("UserDatas");
                }
                return _UserDatas;
            }
        }
        private ObjectSet<UserData> _UserDatas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AvailabilityData> AvailabilityDatas
        {
            get
            {
                if ((_AvailabilityDatas == null))
                {
                    _AvailabilityDatas = base.CreateObjectSet<AvailabilityData>("AvailabilityDatas");
                }
                return _AvailabilityDatas;
            }
        }
        private ObjectSet<AvailabilityData> _AvailabilityDatas;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GameDatas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGameDatas(GameData gameData)
        {
            base.AddObject("GameDatas", gameData);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GameLocationDatas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGameLocationDatas(GameLocationData gameLocationData)
        {
            base.AddObject("GameLocationDatas", gameLocationData);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PlayerDatas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPlayerDatas(PlayerData playerData)
        {
            base.AddObject("PlayerDatas", playerData);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PlayerGroupDatas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPlayerGroupDatas(PlayerGroupData playerGroupData)
        {
            base.AddObject("PlayerGroupDatas", playerGroupData);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SeasonDatas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSeasonDatas(SeasonData seasonData)
        {
            base.AddObject("SeasonDatas", seasonData);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TeamDatas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTeamDatas(TeamData teamData)
        {
            base.AddObject("TeamDatas", teamData);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TeamOwnerDatas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTeamOwnerDatas(TeamOwnerData teamOwnerData)
        {
            base.AddObject("TeamOwnerDatas", teamOwnerData);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TeamPrivacyDatas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTeamPrivacyDatas(TeamPrivacyData teamPrivacyData)
        {
            base.AddObject("TeamPrivacyDatas", teamPrivacyData);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UserDatas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUserDatas(UserData userData)
        {
            base.AddObject("UserDatas", userData);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AvailabilityDatas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAvailabilityDatas(AvailabilityData availabilityData)
        {
            base.AddObject("AvailabilityDatas", availabilityData);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseModel", Name="AvailabilityData")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AvailabilityData : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AvailabilityData object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="playerId">Initial value of the PlayerId property.</param>
        /// <param name="eventId">Initial value of the EventId property.</param>
        public static AvailabilityData CreateAvailabilityData(global::System.Int32 id, global::System.Int32 playerId, global::System.Int32 eventId)
        {
            AvailabilityData availabilityData = new AvailabilityData();
            availabilityData.Id = id;
            availabilityData.PlayerId = playerId;
            availabilityData.EventId = eventId;
            return availabilityData;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PlayerId
        {
            get
            {
                return _PlayerId;
            }
            set
            {
                OnPlayerIdChanging(value);
                ReportPropertyChanging("PlayerId");
                _PlayerId = StructuralObject.SetValidValue(value, "PlayerId");
                ReportPropertyChanged("PlayerId");
                OnPlayerIdChanged();
            }
        }
        private global::System.Int32 _PlayerId;
        partial void OnPlayerIdChanging(global::System.Int32 value);
        partial void OnPlayerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EventId
        {
            get
            {
                return _EventId;
            }
            set
            {
                OnEventIdChanging(value);
                ReportPropertyChanging("EventId");
                _EventId = StructuralObject.SetValidValue(value, "EventId");
                ReportPropertyChanged("EventId");
                OnEventIdChanged();
            }
        }
        private global::System.Int32 _EventId;
        partial void OnEventIdChanging(global::System.Int32 value);
        partial void OnEventIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> AdminStatus
        {
            get
            {
                return _AdminStatus;
            }
            set
            {
                OnAdminStatusChanging(value);
                ReportPropertyChanging("AdminStatus");
                _AdminStatus = StructuralObject.SetValidValue(value, "AdminStatus");
                ReportPropertyChanged("AdminStatus");
                OnAdminStatusChanged();
            }
        }
        private Nullable<global::System.Int16> _AdminStatus;
        partial void OnAdminStatusChanging(Nullable<global::System.Int16> value);
        partial void OnAdminStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> RepliedStatus
        {
            get
            {
                return _RepliedStatus;
            }
            set
            {
                OnRepliedStatusChanging(value);
                ReportPropertyChanging("RepliedStatus");
                _RepliedStatus = StructuralObject.SetValidValue(value, "RepliedStatus");
                ReportPropertyChanged("RepliedStatus");
                OnRepliedStatusChanged();
            }
        }
        private Nullable<global::System.Int16> _RepliedStatus;
        partial void OnRepliedStatusChanging(Nullable<global::System.Int16> value);
        partial void OnRepliedStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EmailSent
        {
            get
            {
                return _EmailSent;
            }
            set
            {
                OnEmailSentChanging(value);
                ReportPropertyChanging("EmailSent");
                _EmailSent = StructuralObject.SetValidValue(value, "EmailSent");
                ReportPropertyChanged("EmailSent");
                OnEmailSentChanged();
            }
        }
        private Nullable<global::System.DateTime> _EmailSent;
        partial void OnEmailSentChanging(Nullable<global::System.DateTime> value);
        partial void OnEmailSentChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseModel", Name="GameData")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GameData : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GameData object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="homeTeamId">Initial value of the HomeTeamId property.</param>
        /// <param name="awayTeamId">Initial value of the AwayTeamId property.</param>
        /// <param name="seasonId">Initial value of the SeasonId property.</param>
        public static GameData CreateGameData(global::System.Int32 id, global::System.Int32 homeTeamId, global::System.Int32 awayTeamId, global::System.Int32 seasonId)
        {
            GameData gameData = new GameData();
            gameData.Id = id;
            gameData.HomeTeamId = homeTeamId;
            gameData.AwayTeamId = awayTeamId;
            gameData.SeasonId = seasonId;
            return gameData;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 HomeTeamId
        {
            get
            {
                return _HomeTeamId;
            }
            set
            {
                OnHomeTeamIdChanging(value);
                ReportPropertyChanging("HomeTeamId");
                _HomeTeamId = StructuralObject.SetValidValue(value, "HomeTeamId");
                ReportPropertyChanged("HomeTeamId");
                OnHomeTeamIdChanged();
            }
        }
        private global::System.Int32 _HomeTeamId;
        partial void OnHomeTeamIdChanging(global::System.Int32 value);
        partial void OnHomeTeamIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AwayTeamId
        {
            get
            {
                return _AwayTeamId;
            }
            set
            {
                OnAwayTeamIdChanging(value);
                ReportPropertyChanging("AwayTeamId");
                _AwayTeamId = StructuralObject.SetValidValue(value, "AwayTeamId");
                ReportPropertyChanged("AwayTeamId");
                OnAwayTeamIdChanged();
            }
        }
        private global::System.Int32 _AwayTeamId;
        partial void OnAwayTeamIdChanging(global::System.Int32 value);
        partial void OnAwayTeamIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SeasonId
        {
            get
            {
                return _SeasonId;
            }
            set
            {
                OnSeasonIdChanging(value);
                ReportPropertyChanging("SeasonId");
                _SeasonId = StructuralObject.SetValidValue(value, "SeasonId");
                ReportPropertyChanged("SeasonId");
                OnSeasonIdChanged();
            }
        }
        private global::System.Int32 _SeasonId;
        partial void OnSeasonIdChanging(global::System.Int32 value);
        partial void OnSeasonIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OpponentName
        {
            get
            {
                return _OpponentName;
            }
            set
            {
                OnOpponentNameChanging(value);
                ReportPropertyChanging("OpponentName");
                _OpponentName = StructuralObject.SetValidValue(value, true, "OpponentName");
                ReportPropertyChanged("OpponentName");
                OnOpponentNameChanged();
            }
        }
        private global::System.String _OpponentName;
        partial void OnOpponentNameChanging(global::System.String value);
        partial void OnOpponentNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value, "Date");
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Date;
        partial void OnDateChanging(Nullable<global::System.DateTime> value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> ScoredPoints
        {
            get
            {
                return _ScoredPoints;
            }
            set
            {
                OnScoredPointsChanging(value);
                ReportPropertyChanging("ScoredPoints");
                _ScoredPoints = StructuralObject.SetValidValue(value, "ScoredPoints");
                ReportPropertyChanged("ScoredPoints");
                OnScoredPointsChanged();
            }
        }
        private Nullable<global::System.Int16> _ScoredPoints;
        partial void OnScoredPointsChanging(Nullable<global::System.Int16> value);
        partial void OnScoredPointsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> AllowedPoints
        {
            get
            {
                return _AllowedPoints;
            }
            set
            {
                OnAllowedPointsChanging(value);
                ReportPropertyChanging("AllowedPoints");
                _AllowedPoints = StructuralObject.SetValidValue(value, "AllowedPoints");
                ReportPropertyChanged("AllowedPoints");
                OnAllowedPointsChanged();
            }
        }
        private Nullable<global::System.Int16> _AllowedPoints;
        partial void OnAllowedPointsChanging(Nullable<global::System.Int16> value);
        partial void OnAllowedPointsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> TiePoints
        {
            get
            {
                return _TiePoints;
            }
            set
            {
                OnTiePointsChanging(value);
                ReportPropertyChanging("TiePoints");
                _TiePoints = StructuralObject.SetValidValue(value, "TiePoints");
                ReportPropertyChanged("TiePoints");
                OnTiePointsChanged();
            }
        }
        private Nullable<global::System.Int16> _TiePoints;
        partial void OnTiePointsChanging(Nullable<global::System.Int16> value);
        partial void OnTiePointsChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseModel", Name="GameLocationData")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GameLocationData : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GameLocationData object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="gameId">Initial value of the GameId property.</param>
        public static GameLocationData CreateGameLocationData(global::System.Int32 id, global::System.Int32 gameId)
        {
            GameLocationData gameLocationData = new GameLocationData();
            gameLocationData.Id = id;
            gameLocationData.GameId = gameId;
            return gameLocationData;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GameId
        {
            get
            {
                return _GameId;
            }
            set
            {
                OnGameIdChanging(value);
                ReportPropertyChanging("GameId");
                _GameId = StructuralObject.SetValidValue(value, "GameId");
                ReportPropertyChanged("GameId");
                OnGameIdChanged();
            }
        }
        private global::System.Int32 _GameId;
        partial void OnGameIdChanging(global::System.Int32 value);
        partial void OnGameIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true, "Description");
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Link
        {
            get
            {
                return _Link;
            }
            set
            {
                OnLinkChanging(value);
                ReportPropertyChanging("Link");
                _Link = StructuralObject.SetValidValue(value, true, "Link");
                ReportPropertyChanged("Link");
                OnLinkChanged();
            }
        }
        private global::System.String _Link;
        partial void OnLinkChanging(global::System.String value);
        partial void OnLinkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Street
        {
            get
            {
                return _Street;
            }
            set
            {
                OnStreetChanging(value);
                ReportPropertyChanging("Street");
                _Street = StructuralObject.SetValidValue(value, true, "Street");
                ReportPropertyChanged("Street");
                OnStreetChanged();
            }
        }
        private global::System.String _Street;
        partial void OnStreetChanging(global::System.String value);
        partial void OnStreetChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true, "City");
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Postal
        {
            get
            {
                return _Postal;
            }
            set
            {
                OnPostalChanging(value);
                ReportPropertyChanging("Postal");
                _Postal = StructuralObject.SetValidValue(value, true, "Postal");
                ReportPropertyChanged("Postal");
                OnPostalChanged();
            }
        }
        private global::System.String _Postal;
        partial void OnPostalChanging(global::System.String value);
        partial void OnPostalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String InternalLocation
        {
            get
            {
                return _InternalLocation;
            }
            set
            {
                OnInternalLocationChanging(value);
                ReportPropertyChanging("InternalLocation");
                _InternalLocation = StructuralObject.SetValidValue(value, true, "InternalLocation");
                ReportPropertyChanged("InternalLocation");
                OnInternalLocationChanged();
            }
        }
        private global::System.String _InternalLocation;
        partial void OnInternalLocationChanging(global::System.String value);
        partial void OnInternalLocationChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseModel", Name="PlayerData")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PlayerData : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PlayerData object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="groupId">Initial value of the GroupId property.</param>
        public static PlayerData CreatePlayerData(global::System.Int32 id, global::System.Int32 groupId)
        {
            PlayerData playerData = new PlayerData();
            playerData.Id = id;
            playerData.GroupId = groupId;
            return playerData;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, true, "Phone");
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true, "Email");
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true, "LastName");
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true, "FirstName");
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GroupId
        {
            get
            {
                return _GroupId;
            }
            set
            {
                OnGroupIdChanging(value);
                ReportPropertyChanging("GroupId");
                _GroupId = StructuralObject.SetValidValue(value, "GroupId");
                ReportPropertyChanged("GroupId");
                OnGroupIdChanged();
            }
        }
        private global::System.Int32 _GroupId;
        partial void OnGroupIdChanging(global::System.Int32 value);
        partial void OnGroupIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Position
        {
            get
            {
                return _Position;
            }
            set
            {
                OnPositionChanging(value);
                ReportPropertyChanging("Position");
                _Position = StructuralObject.SetValidValue(value, true, "Position");
                ReportPropertyChanged("Position");
                OnPositionChanged();
            }
        }
        private global::System.String _Position;
        partial void OnPositionChanging(global::System.String value);
        partial void OnPositionChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseModel", Name="PlayerGroupData")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PlayerGroupData : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PlayerGroupData object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="teamId">Initial value of the TeamId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="order">Initial value of the Order property.</param>
        public static PlayerGroupData CreatePlayerGroupData(global::System.Int32 id, global::System.Int32 teamId, global::System.String name, global::System.Int16 order)
        {
            PlayerGroupData playerGroupData = new PlayerGroupData();
            playerGroupData.Id = id;
            playerGroupData.TeamId = teamId;
            playerGroupData.Name = name;
            playerGroupData.Order = order;
            return playerGroupData;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TeamId
        {
            get
            {
                return _TeamId;
            }
            set
            {
                OnTeamIdChanging(value);
                ReportPropertyChanging("TeamId");
                _TeamId = StructuralObject.SetValidValue(value, "TeamId");
                ReportPropertyChanged("TeamId");
                OnTeamIdChanged();
            }
        }
        private global::System.Int32 _TeamId;
        partial void OnTeamIdChanging(global::System.Int32 value);
        partial void OnTeamIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 Order
        {
            get
            {
                return _Order;
            }
            set
            {
                OnOrderChanging(value);
                ReportPropertyChanging("Order");
                _Order = StructuralObject.SetValidValue(value, "Order");
                ReportPropertyChanged("Order");
                OnOrderChanged();
            }
        }
        private global::System.Int16 _Order;
        partial void OnOrderChanging(global::System.Int16 value);
        partial void OnOrderChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseModel", Name="SeasonData")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SeasonData : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SeasonData object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="order">Initial value of the Order property.</param>
        public static SeasonData CreateSeasonData(global::System.Int32 id, global::System.Int16 type, global::System.String name, global::System.Int16 order)
        {
            SeasonData seasonData = new SeasonData();
            seasonData.Id = id;
            seasonData.Type = type;
            seasonData.Name = name;
            seasonData.Order = order;
            return seasonData;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, "Type");
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.Int16 _Type;
        partial void OnTypeChanging(global::System.Int16 value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LeagueId
        {
            get
            {
                return _LeagueId;
            }
            set
            {
                OnLeagueIdChanging(value);
                ReportPropertyChanging("LeagueId");
                _LeagueId = StructuralObject.SetValidValue(value, "LeagueId");
                ReportPropertyChanged("LeagueId");
                OnLeagueIdChanged();
            }
        }
        private Nullable<global::System.Int32> _LeagueId;
        partial void OnLeagueIdChanging(Nullable<global::System.Int32> value);
        partial void OnLeagueIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TeamId
        {
            get
            {
                return _TeamId;
            }
            set
            {
                OnTeamIdChanging(value);
                ReportPropertyChanging("TeamId");
                _TeamId = StructuralObject.SetValidValue(value, "TeamId");
                ReportPropertyChanged("TeamId");
                OnTeamIdChanged();
            }
        }
        private Nullable<global::System.Int32> _TeamId;
        partial void OnTeamIdChanging(Nullable<global::System.Int32> value);
        partial void OnTeamIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 Order
        {
            get
            {
                return _Order;
            }
            set
            {
                OnOrderChanging(value);
                ReportPropertyChanging("Order");
                _Order = StructuralObject.SetValidValue(value, "Order");
                ReportPropertyChanged("Order");
                OnOrderChanged();
            }
        }
        private global::System.Int16 _Order;
        partial void OnOrderChanging(global::System.Int16 value);
        partial void OnOrderChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseModel", Name="TeamData")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TeamData : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TeamData object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="resultsView">Initial value of the ResultsView property.</param>
        public static TeamData CreateTeamData(global::System.Int32 id, global::System.String name, global::System.Int16 resultsView)
        {
            TeamData teamData = new TeamData();
            teamData.Id = id;
            teamData.Name = name;
            teamData.ResultsView = resultsView;
            return teamData;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Announcements
        {
            get
            {
                return _Announcements;
            }
            set
            {
                OnAnnouncementsChanging(value);
                ReportPropertyChanging("Announcements");
                _Announcements = StructuralObject.SetValidValue(value, true, "Announcements");
                ReportPropertyChanged("Announcements");
                OnAnnouncementsChanged();
            }
        }
        private global::System.String _Announcements;
        partial void OnAnnouncementsChanging(global::System.String value);
        partial void OnAnnouncementsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Banner
        {
            get
            {
                return _Banner;
            }
            set
            {
                OnBannerChanging(value);
                ReportPropertyChanging("Banner");
                _Banner = StructuralObject.SetValidValue(value, true, "Banner");
                ReportPropertyChanged("Banner");
                OnBannerChanged();
            }
        }
        private global::System.String _Banner;
        partial void OnBannerChanging(global::System.String value);
        partial void OnBannerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 ResultsView
        {
            get
            {
                return _ResultsView;
            }
            set
            {
                OnResultsViewChanging(value);
                ReportPropertyChanging("ResultsView");
                _ResultsView = StructuralObject.SetValidValue(value, "ResultsView");
                ReportPropertyChanged("ResultsView");
                OnResultsViewChanged();
            }
        }
        private global::System.Int16 _ResultsView;
        partial void OnResultsViewChanging(global::System.Int16 value);
        partial void OnResultsViewChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Postal
        {
            get
            {
                return _Postal;
            }
            set
            {
                OnPostalChanging(value);
                ReportPropertyChanging("Postal");
                _Postal = StructuralObject.SetValidValue(value, true, "Postal");
                ReportPropertyChanged("Postal");
                OnPostalChanged();
            }
        }
        private global::System.String _Postal;
        partial void OnPostalChanging(global::System.String value);
        partial void OnPostalChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseModel", Name="TeamOwnerData")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TeamOwnerData : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TeamOwnerData object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="teamId">Initial value of the TeamId property.</param>
        public static TeamOwnerData CreateTeamOwnerData(global::System.Int32 id, global::System.Int32 userId, global::System.Int32 teamId)
        {
            TeamOwnerData teamOwnerData = new TeamOwnerData();
            teamOwnerData.Id = id;
            teamOwnerData.UserId = userId;
            teamOwnerData.TeamId = teamId;
            return teamOwnerData;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value, "UserId");
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TeamId
        {
            get
            {
                return _TeamId;
            }
            set
            {
                OnTeamIdChanging(value);
                ReportPropertyChanging("TeamId");
                _TeamId = StructuralObject.SetValidValue(value, "TeamId");
                ReportPropertyChanged("TeamId");
                OnTeamIdChanged();
            }
        }
        private global::System.Int32 _TeamId;
        partial void OnTeamIdChanging(global::System.Int32 value);
        partial void OnTeamIdChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseModel", Name="TeamPrivacyData")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TeamPrivacyData : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TeamPrivacyData object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="teamId">Initial value of the TeamId property.</param>
        /// <param name="homePage">Initial value of the HomePage property.</param>
        /// <param name="roster">Initial value of the Roster property.</param>
        public static TeamPrivacyData CreateTeamPrivacyData(global::System.Int32 id, global::System.Int32 teamId, global::System.Boolean homePage, global::System.Boolean roster)
        {
            TeamPrivacyData teamPrivacyData = new TeamPrivacyData();
            teamPrivacyData.Id = id;
            teamPrivacyData.TeamId = teamId;
            teamPrivacyData.HomePage = homePage;
            teamPrivacyData.Roster = roster;
            return teamPrivacyData;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TeamId
        {
            get
            {
                return _TeamId;
            }
            set
            {
                OnTeamIdChanging(value);
                ReportPropertyChanging("TeamId");
                _TeamId = StructuralObject.SetValidValue(value, "TeamId");
                ReportPropertyChanged("TeamId");
                OnTeamIdChanged();
            }
        }
        private global::System.Int32 _TeamId;
        partial void OnTeamIdChanging(global::System.Int32 value);
        partial void OnTeamIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean HomePage
        {
            get
            {
                return _HomePage;
            }
            set
            {
                OnHomePageChanging(value);
                ReportPropertyChanging("HomePage");
                _HomePage = StructuralObject.SetValidValue(value, "HomePage");
                ReportPropertyChanged("HomePage");
                OnHomePageChanged();
            }
        }
        private global::System.Boolean _HomePage;
        partial void OnHomePageChanging(global::System.Boolean value);
        partial void OnHomePageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Roster
        {
            get
            {
                return _Roster;
            }
            set
            {
                OnRosterChanging(value);
                ReportPropertyChanging("Roster");
                _Roster = StructuralObject.SetValidValue(value, "Roster");
                ReportPropertyChanged("Roster");
                OnRosterChanged();
            }
        }
        private global::System.Boolean _Roster;
        partial void OnRosterChanging(global::System.Boolean value);
        partial void OnRosterChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseModel", Name="UserData")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserData : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UserData object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="username">Initial value of the Username property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        public static UserData CreateUserData(global::System.Int32 id, global::System.String username, global::System.String email)
        {
            UserData userData = new UserData();
            userData.Id = id;
            userData.Username = username;
            userData.Email = email;
            return userData;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, false, "Username");
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false, "Email");
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ActiveTeamId
        {
            get
            {
                return _ActiveTeamId;
            }
            set
            {
                OnActiveTeamIdChanging(value);
                ReportPropertyChanging("ActiveTeamId");
                _ActiveTeamId = StructuralObject.SetValidValue(value, "ActiveTeamId");
                ReportPropertyChanged("ActiveTeamId");
                OnActiveTeamIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ActiveTeamId;
        partial void OnActiveTeamIdChanging(Nullable<global::System.Int32> value);
        partial void OnActiveTeamIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Password
        {
            get
            {
                return StructuralObject.GetValidValue(_Password);
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true, "Password");
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.Byte[] _Password;
        partial void OnPasswordChanging(global::System.Byte[] value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastSeen
        {
            get
            {
                return _LastSeen;
            }
            set
            {
                OnLastSeenChanging(value);
                ReportPropertyChanging("LastSeen");
                _LastSeen = StructuralObject.SetValidValue(value, "LastSeen");
                ReportPropertyChanged("LastSeen");
                OnLastSeenChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastSeen;
        partial void OnLastSeenChanging(Nullable<global::System.DateTime> value);
        partial void OnLastSeenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Reset
        {
            get
            {
                return _Reset;
            }
            set
            {
                OnResetChanging(value);
                ReportPropertyChanging("Reset");
                _Reset = StructuralObject.SetValidValue(value, true, "Reset");
                ReportPropertyChanged("Reset");
                OnResetChanged();
            }
        }
        private global::System.String _Reset;
        partial void OnResetChanging(global::System.String value);
        partial void OnResetChanged();

        #endregion

    }

    #endregion

}
